mysql-docker:
  container_name: mysql_docker
  image: mysql:5.7
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=realtime_notifer
    - MYSQL_USER=sla
    - MYSQL_PASSWORD=sla

boot-rethink:
  container_name: rethinkdb_docker
  image: rethinkdb
  ports:
  - 8080:8080
  - 28015:28015
  - 29015:29015

realtime-notifer-docker:
  container_name: realtime_notifer
  image: slawekhaa/realtime_notifer
  links:
    - mysql-docker:mysql
    - boot-rethink:rethink
  ports:
    - 8090:8090
